"use strict"
var v1 = /^[a-zA-Z]+[\sa-zA-Z]*$/;/*VALIDAR LETRAS UN ESPACIO EN BLANCO*/
var v2 = /^[0-9]*$/;/*VALIDACION DE NUMEROS ENTEROS POSITIVOS*/
var v3 = /^[0-9]+[\.]?[0-9]*$/;/*VALIDADCION DE NUMEROS POSITIVOS INCLUIDOS LOS DECIMALES*/
var v4 = /^\S@\S+\.\S/;/*VALIDACION DE CORREOS*/